# -*- coding: utf-8 -*-
"""Cópia de Imersão IA Alura + Google Gemini - Aula 05 - Agentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WR2DZOsyv6tPsU1QeHtAZ6ystu_UqKmy
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-genai

# Configura a API Key do Google Gemini

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

# Configura o cliente da SDK do Gemini

from google import genai

client = genai.Client()

MODEL_ID = "gemini-2.0-flash"

# Pergunta ao Gemini uma informação mais recente que seu conhecimento

from IPython.display import HTML, Markdown

# Perguntar pro modelo quando é a próxima imersão de IA
resposta = client.models.generate_content(model=MODEL_ID, contents="Quando é a próxima imersão com Google Gemini da Alura")

# Exibe a resposta na tela
display(Markdown(f"Resposta:\n {resposta.text}"))

# Pergunta ao Gemini uma informação utilizando a busca do Google como contexto

response = client.models.generate_content(
    model=MODEL_ID,
    contents='Quando é a próxima Imersão IA com Google Gemini da Alura?',
    config={"tools":[{"google_search": {}}]}
    # Inserir a tool de busca do Google
)

# Exibe a resposta na tela
display(Markdown(f"Resposta:\n {response.text}"))

# Exibe a busca
print(f"Busca realizada: {response.candidates[0].grounding_metadata.web_search_queries}")
# Exibe as URLs nas quais ele se baseou
print(f"Páginas utilizadas na resposta: {', '.join([site.web.title for site in response.candidates[0].grounding_metadata.grounding_chunks])}")
print()
display(HTML(response.candidates[0].grounding_metadata.search_entry_point.rendered_content))

!pip install -q google-adk

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types  # Para criar conteúdos (Content e Part)
from datetime import date
import textwrap # Para formatar melhor a saída de texto
from IPython.display import display, Markdown # Para exibir texto formatado no Colab
import requests # Para fazer requisições HTTP
import warnings

warnings.filterwarnings("ignore")

# Função auxiliar que envia uma mensagem para um agente via Runner e retorna a resposta final
def call_agent(agent: Agent, message_text: str) -> str:
    # Cria um serviço de sessão em memória
    session_service = InMemorySessionService()
    # Cria uma nova sessão (você pode personalizar os IDs conforme necessário)
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    # Cria um Runner para o agente
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    # Cria o conteúdo da mensagem de entrada
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    # Itera assincronamente pelos eventos retornados durante a execução do agente
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
          for part in event.content.parts:
            if part.text is not None:
              final_response += part.text
              final_response += "\n"
    return final_response

# Função auxiliar para exibir texto formatado em Markdown no Colab
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

# --- Agente 1: Buscador de Notícias --- #

def agente_buscador(topico, data_de_hoje):
    buscador = Agent(
        name="agente_buscador",
        model="gemini-2.0-flash",
        description="Agente que busca notícias sobre o tópico indicado",
        tools=[google_search],
        instruction = """Você é um assistente de pesquisa. A sua tarefa é usar a ferramenta de busca do google (google_search)
        para recuperar as últimas noticias de lançamentos muito relevantes sobre o tópico abaixo.
        Eses lançamentos devem ser atuais, de no máximo 30 dias atrás.
        """
    )

    entrada_do_agente_buscador = f"Tópico: {topico}\nData de hoje: {data_de_hoje}"
    # Executa o agente
    lancamentos = call_agent(buscador, entrada_do_agente_buscador)
    return lancamentos

# --- Agente 2: Planejador de posts --- #

def agente_planejador(topico, lancamentos_buscados):
    planejador = Agent(
        name="agente_planejador",
        model="gemini-2.0-flash",
        # Inserir as instruções do Agente Planejador #################################################
        instruction="""
        Você é um planejador de conteudo, especialista em redes sociais.
        Com base na lista de lancamentos mas recentes e relevantes buscador, você deve:
        usar a ferramenta de busca do Google(google_search) para criar um planosobre cada um deles.
        Ao final, você ira escolher o tema mais relevante entre eles com base nas suas pesquisas e retornar esse tema, seus pontos mais relevantes,
        e um plano com os assuntos a serem abordados no post que será escrito posteriormente.
        """,
        description="Agente que planeja posts",
        tools=[google_search]
    )

    entrada_do_agente_planejador = f"Tópico:{topico}\nLançamentos buscados: {lancamentos_buscados}"
    # Executa o agente
    plano_do_post = call_agent(planejador, entrada_do_agente_planejador)
    return plano_do_post

# --- Agente 3: Redator do Post --- #

def agente_redator(topico, plano_de_post):
    redator = Agent(
        name="agente_redator",
        model="gemini-2.0-flash",
        instruction="""
            Você é um Redator Criativo especializado em criar posts virais para redes sociais.
            Você escreve posts para a empresa Mainardes, a maior escola online de tecnologia do Brasil.
            Utilize o tema fornecido no plano de post e os pontos mais relevantes fornecidos e, com base nisso,
            escreva um rascunho de post para Instagram sobre o tema indicado.
            O post deve ser engajador, informativo, com linguagem simples e incluir 2 a 4 hashtags no final.
            """,
        description="Agente redator de posts engajadores para Instagram"
    )
    entrada_do_agente_redator = f"Tópico: {topico}\nPlano de post: {plano_de_post}"
    # Executa o agente
    rascunho = call_agent(redator, entrada_do_agente_redator)
    return rascunho

# --- Agente 4: Revisor de Qualidade --- #

def agente_revisor(topico, rascunho_gerado):
    revisor = Agent(
        name="agente_revisor",
        model="gemini-2.0-flash",
        instruction="""
            Você é um Editor e Revisor de Conteúdo meticuloso, especializado em posts para redes sociais, com foco no Instagram.
            Por ter um público jovem, entre 18 e 30 anos, use um tom de escrita adequado.
            Revise o rascunho de post de Instagram abaixo sobre o tópico indicado, verificando clareza, concisão, correção e tom.
            Se o rascunho estiver bom, responda apenas 'O rascunho está ótimo e pronto para publicar!'.
            Caso haja problemas, aponte-os e sugira melhorias.
            """,
        description="Agente revisor de post para redes sociais."

    )
    entrada_do_agente_revisor = f"Tópico: {topico}\nRascunho: {rascunho_gerado}"
    # Executa o agente
    texto_revisado = call_agent(revisor, entrada_do_agente_revisor)
    return texto_revisado

#Ativar agentes criados pela Alura

data_de_hoje = date.today().strftime("%d/%m/%Y")

print("Iniciando o Sistema de Criação de Posts para Instagram com 4 Agentes")

# --- Obter o Tópico do Usuário ---
topico = input("Por favor, digite o TÓPICO sobre o qual você quer criar o post de tendências: ")

if not topico:
  print("Você esqueceu de digitar o tópico!")
else:
  print(f"Maravilha! Vamos criar o post sobre novidades em {topico} ")
  lancamentos_buscados = agente_buscador(topico, data_de_hoje);
  display(to_markdown(lancamentos_buscados))
  print("-------------------")
  plano_de_post = agente_planejador(topico, lancamentos_buscados);
  display(to_markdown(plano_de_post))
  print("-------------------")
  rascunho_gerado = agente_redator(topico, plano_de_post);
  display(to_markdown(rascunho_gerado))
  print("-------------------")
  texto_revisado = agente_revisor(topico, rascunho_gerado);
  display(to_markdown(texto_revisado))

# --- Agente 1: Buscador de Notícias --- #

def agente_entendedor(topico):
    buscador = Agent(
        name="agente_entendedor",
        model="gemini-2.0-flash",
        description="Agente que busca sobre o curso feito",
        tools=[google_search],
        instruction = """Você vai buscar sobre o curso que a pessoa fez no tópico abaixo.
        Pesquisar as materias e competencias que foram estudadas.
        """
    )

    entrada_do_agente_buscador = f"Tópico: {topico}"
    # Executa o agente
    entendimento = call_agent(buscador, entrada_do_agente_buscador)
    return entendimento;

# --- Agente 2: Criador de post Linkedin --- #

def agente_criador(topico, plano_de_post):
    redator = Agent(
        name="agente_criador",
        model="gemini-2.0-flash",
        instruction="""
            Você é a pessoa que realizou o curso, e quer postar o certificado com uma frase sobre o curso.
            Com base nos dados recebidos escreva de forma que chame a atenção dos recrutadores e de forma formal, sobre o curso realizado.
            Sempre levando em consideração foco na relevância do curso para o mercado.
            """,
        description="Agente para criar post linkedin"
    )
    entrada_do_agente_redator = f"Tópico: {topico}\nPlano de post: {plano_de_post}"
    # Executa o agente
    frase = call_agent(redator, entrada_do_agente_redator)
    return frase

#Ativar agentes criados por mim para o Linkedin

print("Iniciando o Sistema de Criação de Posts para chamar atenção de recrutadores")

# --- Obter o Tópico do Usuário ---
topico = input("Escreva brevemente sobre o curso que você realizou e a plataforma ")

if not topico:
  print("Você esqueceu de digitar o tópico!")
else:
  print(f"Maravilha! Vamos criar o post sobre o curso {topico} ")
  entendimento = agente_entendedor(topico);
  frase = agente_criador(topico, entendimento);
  print("Segue o seu post para o Linkedin: \n")
  display(to_markdown(frase))

# --- Agente 1: Buscador de Notícias --- #

def agente_entendedorSobre(topico):
    buscador = Agent(
        name="agente_entendedor",
        model="gemini-2.0-flash",
        description="Agente que busca sobre o tema que vai ser falada no vídeo",
        tools=[google_search],
        instruction = """Você vai buscar sobre o tema que a pessoa falar usando sempre os tópicos mais recentes.
        """
    )

    entrada_do_agente_buscador = f"Tópico: {topico}"
    # Executa o agente
    entendedorSobre = call_agent(buscador, entrada_do_agente_buscador)
    return entendedorSobre;

def agente_roteiro(topico, plano_de_post):
    redator = Agent(
        name="agente_criador",
        model="gemini-2.0-flash",
        instruction="""
            Você é a pessoa que vai criar o roteiro para um vídeo para os jovens, colocando falas e imagens referente a fala do assunto que foi
            colocado pela pessoa
            """,
        description="Agente para criar o roteiro"
    )
    entrada_do_agente_redator = f"Tópico: {topico}\nPlano de post: {plano_de_post}"
    # Executa o agente
    roteiro = call_agent(redator, entrada_do_agente_redator)
    return roteiro

#Ativar agentes criados por mim para geração de roteiros

print("Iniciando o Sistema de Criação de roteiros")

# --- Obter o Tópico do Usuário ---
topico = input("Escreva brevemente sobre o que você quer criar ")

if not topico:
  print("Você esqueceu de digitar o tópico!")
else:
  print(f"Maravilha! Vamos criar o roteiro: {topico} ");
  entendedor = agente_entendedorSobre(topico);
  frase = agente_roteiro(topico, entendedor);
  print("Segue o seu post para o Roteiro: \n")
  display(to_markdown(frase))